# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Pagina de Carlos
# Description of the Site
description: Administrador de sistemas informáticos en Red                  Y                          Especialista en Ciberseguridad
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /imagenes/about/carlos.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: cdiazmaguadulce@gmail.com
facebook_username: Carlos Diaz Montes
twitter_username: Carlosdm_21
instagram_username: carlosdm_21
linkedin_username: carlos Díaz Montes
github_username:  Cdiazm21
youtube_channel_id: UCHhXWUvoyT-zyamYstqFjKw
spotify_username: cdiazmaguadulce
telefono: 629594937

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Carlos

# Name of the Author
author-name: Carlos
# URL for the Image of the Author
author-image: /assets/images/FotoCurricuum_CarlosDiaz_Recorte.jpg
# 60 Words About the Author
author-about: >
  Tengo el Grado Superior de Administración de Sistemas Informáticos en Red y una Especialización en Ciberseguridad, aparte de distintos cursos online relacionados con la informática que pueden encontrar en mi currículum. También poseo un nivel medio-alto de inglés, tanto escrito como hablado, y mi nivel de francés es básico.

  Tengo 6 meses de experiencia en una empresa de Informática donde realizábamos tanto soporte de hardware como de software para otras empresas, y estaba encargado de la seguridad y mantenimiento del servidor donde estaban alojadas las páginas webs de los clientes. A su vez, también estuve desarrollando algunas páginas en Wordpress. Durante mi estancia en esta empresa, estuve a cargo de un estudiante de informática que realizaba allí sus prácticas de grado medio.

  Me considero una persona trabajadora, madura y tranquila. Sé trabajar en situaciones de estrés y busco una empresa donde me permita seguir ampliando mis conocimientos y desarrollarme como trabajador. Dispongo de carnet de conducir y coche propio. Actualmente vivo en Andalucía, Almería, pero no tengo ningún inconveniente en vivir en otra ciudad. Estoy dispuesto a hacer viajes de empresa sin problemas, tanto dentro de España como a otros países.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Cdiazm21 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
