# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Pagina de Carlos
# Description of the Site
description: Administrador de sistemas informaticos en red
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /imagenes/about/carlos.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: cdiazmaguadulce@gmail.com
facebook_username: Carlos Diaz Montes
twitter_username: Carlosdm_21
instagram_username: carlosdm_21
linkedin_username: carlos Díaz Montes
github_username:  Cdiazm21
youtube_channel_id: UCHhXWUvoyT-zyamYstqFjKw
spotify_username: cdiazmaguadulce
telefono: 629594937

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Carlos

# Name of the Author
author-name: Carlos
# URL for the Image of the Author
author-image: /assets/images/FotoCurricuum_CarlosDiaz_Recorte.jpg
# 60 Words About the Author
author-about: Esta web es una forma de mostrar mis proyectos realizados, mis cursos realizados, mi curriculum... Es una forma de mostrar lo que soy para las empresas a las que se esten replanteando contratarme.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Cdiazm21 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
